// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgWjEHzLYprJN6pphoNQD0Dtdn0hAn30',
    appId: '1:701160550215:web:977c5f04e1e343a6bbe662',
    messagingSenderId: '701160550215',
    projectId: 'caffeine-connect-5c357',
    authDomain: 'caffeine-connect-5c357.firebaseapp.com',
    storageBucket: 'caffeine-connect-5c357.appspot.com',
    measurementId: 'G-F6D1ZC0KKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTutQQ_wOmYWUh8IYZYb1ESvNsA1bbmBQ',
    appId: '1:701160550215:android:141ee93c85156e43bbe662',
    messagingSenderId: '701160550215',
    projectId: 'caffeine-connect-5c357',
    storageBucket: 'caffeine-connect-5c357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDRxNNfmc8QsX0RhMn1J7Jst0EDbli9Y',
    appId: '1:701160550215:ios:673988afd483cd5ebbe662',
    messagingSenderId: '701160550215',
    projectId: 'caffeine-connect-5c357',
    storageBucket: 'caffeine-connect-5c357.appspot.com',
    iosBundleId: 'com.example.caffeineConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDRxNNfmc8QsX0RhMn1J7Jst0EDbli9Y',
    appId: '1:701160550215:ios:3f1eadc1e57db42dbbe662',
    messagingSenderId: '701160550215',
    projectId: 'caffeine-connect-5c357',
    storageBucket: 'caffeine-connect-5c357.appspot.com',
    iosBundleId: 'com.example.caffeineConnect.RunnerTests',
  );
}
